name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Smoke Tests
        shell: pwsh
        run: ./run-smoke.ps1 -SkipBuild

      - name: Pack (Artifacts)
        if: github.ref == 'refs/heads/main'
        run: dotnet pack src/lambda-cek.csproj -c Release -o artifacts

      - name: Archive artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
            name: nupkg
            path: artifacts/*.nupkg